const { chromium } = require('playwright');
(async()=>{
 const browser=await chromium.launch({headless:true,args:['--no-sandbox']});
 const page=await browser.newPage({viewport:{width:1440,height:1060},deviceScaleFactor:1});
 const errors=[];page.on('pageerror',e=>errors.push(e.message));
 await page.goto('http://127.0.0.1:8000');await page.waitForFunction(()=>document.querySelector('#resultTitle').textContent==='Possible obstruction');
 const dir=require('path').resolve('docs/screenshots')+'/';
 await page.screenshot({path:dir+'01_review_workspace.png',fullPage:true});
 await page.getByRole('button',{name:'Bicycle beside paving',exact:true}).click();
 await page.waitForFunction(()=>document.querySelector('#resultTitle').textContent==='No supported overlap detected');
 await page.screenshot({path:dir+'02_beside_paving.png',fullPage:true});
 await page.getByRole('button',{name:'Weak paving signal',exact:true}).click();
 await page.waitForFunction(()=>document.querySelector('#resultTitle').textContent==='More evidence needed');
 await page.screenshot({path:dir+'03_uncertainty.png',fullPage:true});
 await page.getByRole('button',{name:'Possible overlap',exact:true}).click();
 await page.getByRole('button',{name:'3D explanation',exact:true}).click();
 await page.locator('#rotate').fill('30');await page.locator('#rotate').dispatchEvent('input');
 await page.locator('#offset').fill('160');await page.locator('#offset').dispatchEvent('input');
 await page.screenshot({path:dir+'04_interactive_3d.png',fullPage:true});
 await page.locator('#question').fill('How many bicycles?');await page.getByRole('button',{name:'Ask GuidePath'}).click();
 await page.waitForFunction(()=>document.querySelector('#answer').textContent.includes('detected 1'));
 await page.getByRole('button',{name:'Image evidence',exact:true}).click();
 await page.locator('#upload').setInputFiles(require('path').resolve('docs/evidence/supplied_colab_setup.png'));
 await page.waitForFunction(()=>document.querySelector('#resultTitle').textContent==='Inference unavailable');
 await page.screenshot({path:dir+'05_missing_weights_guardrail.png',fullPage:true});
 await page.getByRole('button',{name:'Return to demo'}).click();await page.setViewportSize({width:390,height:844});
 await page.screenshot({path:dir+'06_mobile.png',fullPage:true});
 if(errors.length)throw new Error(errors.join('\n'));
 require('fs').mkdirSync('outputs/verification',{recursive:true});
 require('fs').writeFileSync('outputs/verification/browser_checks.json',JSON.stringify({browser:'Chromium headless',checks:['three fixture outcomes','3D rotation and movement controls','demo count question','real upload missing-weights error without fixture substitution','mobile screenshot'],page_errors:errors,scope:'UI and software checks only; no trained model or live LLM'},null,2));
 await browser.close();console.log('Browser checks and six actual screenshots saved.');
})().catch(e=>{console.error(e);process.exit(1)});
